version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
    volumes:
      - ./services/ui/dist:/app/services/ui/dist:ro
