services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: bfl-api
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./services/ui/dist:/app/ui/dist:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    restart: unless-stopped
