groups:
  - name: bfl_autopilot
    interval: 30s
    rules:
      - alert: BFLAutopilotQueueStuck
        expr: bfl_autopilot_queue_depth > 10
        for: 10m
        labels:
          severity: warning
          service: bfl
          area: autopilot
        annotations:
          summary: "Autopilot queue depth > 10"
          description: "Queue depth high for >10m."
      - alert: BFLAutopilotFailureRatioHigh
        expr: |
          (sum by (type) (rate(bfl_autopilot_failed_total[10m])))/(clamp_min(sum by (type) (rate(bfl_autopilot_started_total[10m])),1e-9)) > 0.1
        for: 10m
        labels:
          severity: critical
          service: bfl
          area: autopilot
        annotations:
          summary: "Autopilot failure ratio > 10% ({{ $labels.type }})"
          description: "Investigate handlers or dependencies."
