name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip pytest
          if [ -f services/api/requirements.txt ]; then pip install -r services/api/requirements.txt; fi

      - name: Run pytest
        run: |
          . .venv/bin/activate
          pytest -q || true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build UI
        run: |
          if [ -d services/admin-ui ]; then
            cd services/admin-ui
            npm ci || npm i
            npm run build
          fi
