name: Remote Smoke

on:
  workflow_dispatch:
    inputs:
      vm_name:
        description: "Yandex Cloud VM name"
        required: true
        default: "bfl-onprem"
      vm_login:
        description: "Linux user on VM (ubuntu/yc-user/ivmsu)"
        required: false
        default: "ubuntu"

concurrency:
  group: remote-smoke
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      YC_ZONE: ${{ secrets.YC_ZONE || 'ru-central1-a' }}
      YC_SA_KEY_JSON: ${{ secrets.YC_SA_KEY_JSON }}
      VM_NAME: ${{ github.event.inputs.vm_name }}
      VM_LOGIN: ${{ github.event.inputs.vm_login }}
      REMOTE_DIR_CANDIDATES: "~/bfl-onprem ~/src/bfl-onprem"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install prerequisites & yc CLI
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq openssh-client lsof
          curl -sSfL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a
          # Добавим yc в PATH для ЭТОГО и последующих шагов
          export PATH="$HOME/yandex-cloud/bin:$PATH"
          echo "$HOME/yandex-cloud/bin" >> "$GITHUB_PATH"
          yc --version

      - name: Configure yc (service account)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${YC_SA_KEY_JSON:-}" || -z "${YC_CLOUD_ID:-}" || -z "${YC_FOLDER_ID:-}" ]]; then
            echo "YC_* secrets are not set"; exit 2
          fi
          printf "%s" "${YC_SA_KEY_JSON}" > sa.json
          # создаём/активируем профиль и настраиваем ключ
          yc config profile create gh-remote-smoke || yc config profile activate gh-remote-smoke
          yc config set service-account-key sa.json
          yc config set cloud-id "${YC_CLOUD_ID}"
          yc config set folder-id "${YC_FOLDER_ID}"
          yc config set compute-default-zone "${YC_ZONE:-ru-central1-a}"
          yc config list
      - name: Generate ephemeral SSH key & add to VM metadata
        id: keygen
        run: |
          set -euo pipefail
          key="$RUNNER_TEMP/yc-smoke-key"
          ssh-keygen -t ed25519 -N "" -C "gh-remote-smoke-$(date +%s)" -f "$key"
          PUB="$(cat "$key.pub")"
          CURR="$(yc compute instance get "$VM_NAME" --format json | jq -r '.metadata["ssh-keys"] // ""')"
          NEW="${CURR:+$CURR$'\n'}${VM_LOGIN}:${PUB}"
          yc compute instance update --name "$VM_NAME" --metadata enable-oslogin=false || true
          yc compute instance update --name "$VM_NAME" --metadata "ssh-keys=${NEW}"
          IP="$(yc compute instance get "$VM_NAME" --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')"
          echo "key=$key" >> "$GITHUB_OUTPUT"
          echo "ip=$IP" >> "$GITHUB_OUTPUT"

      - name: Bring up api+redis on VM
        run: |
          set -euo pipefail
          key="${{ steps.keygen.outputs.key }}"
          ip="${{ steps.keygen.outputs.ip }}"
          ssh -o StrictHostKeyChecking=no -i "$key" "$VM_LOGIN@$ip" <<'SSH'
            set -euo pipefail
            export DEBIAN_FRONTEND=noninteractive
            # 0) git/docker при необходимости
            if ! command -v git >/dev/null 2>&1; then sudo apt-get update -y && sudo apt-get install -y git; fi
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update -y && sudo apt-get install -y docker.io docker-compose-plugin
              sudo systemctl enable --now docker
            fi
            # 1) найти/склонировать/обновить репо
            REPO=
            for d in ~/bfl-onprem ~/src/bfl-onprem; do [ -d "$d/.git" ] && REPO="$d" && break; done
            if [ -z "${REPO:-}" ]; then
              REPO=~/bfl-onprem
              git clone --depth=1 https://github.com/MaksimProkopyev/bfl-onprem-public.git "$REPO"
            else
              cd "$REPO" && git fetch --all --prune && git reset --hard origin/main
            fi
            cd "$REPO"
            # 2) выбрать compose-файлы с fallback, если override отсутствует
            FILES="-f docker-compose.yml"
            [ -f docker-compose.override.yml ] && FILES="$FILES -f docker-compose.override.yml"
            echo "--- docker compose files: $FILES"
            # 3) поднять api+redis, показать диагностику при ошибке
            sudo docker compose $FILES up -d --build api redis || {
              echo "--- docker compose ps ---"; sudo docker compose ps || true
              echo "--- api logs (tail) ---"; sudo docker compose logs --no-color --timestamps --tail=200 api || true
              echo "--- redis logs (tail) ---"; sudo docker compose logs --no-color --timestamps --tail=200 redis || true
              exit 4
            }
            sudo docker compose ps
          SSH
      - name: Create SSH tunnel to 127.0.0.1:8000
        run: |
          set -euo pipefail
          key="${{ steps.keygen.outputs.key }}"
          ip="${{ steps.keygen.outputs.ip }}"
          ssh -o StrictHostKeyChecking=no -i "$key" \
            -fNT -L 18000:127.0.0.1:8000 -o ExitOnForwardFailure=yes \
            -o ServerAliveInterval=30 -o ServerAliveCountMax=3 "$VM_LOGIN@$ip"
          sleep 1
          nc -zv 127.0.0.1 18000

      - name: Remote smoke (via tunnel)
        run: |
          set -euo pipefail
          BASE="http://127.0.0.1:18000"
          for i in {1..60}; do curl -fsS "$BASE/livez" >/dev/null && break || sleep 1; done
          {
            echo "== /livez =="
            curl -fsS "$BASE/livez"
            echo
            echo "== /readyz (status line) =="
            curl -fsSI "$BASE/readyz" | sed -n '1p'
            echo
            echo "== /api/health =="
            curl -fsS "$BASE/api/health"
            echo
            echo "== /metrics (head) =="
            curl -fsS "$BASE/metrics" | sed -n '1,20p'
            echo
            echo "== login flow =="
            h=$(mktemp); c=$(mktemp)
            curl -s -D "$h" -c "$c" "$BASE/autopilot/login" >/dev/null
            csrf=$(grep -E '\sbfl_csrf\s' "$c" | awk '{print $7}')
            echo "csrf=$csrf"
            echo -n "POST /api/auth/login → "
            curl -s -o /dev/null -w '%{http_code}\n' -b "$c" -c "$c" -H "X-CSRF-Token: $csrf" \
              -F 'username=demo' -F 'password=demo' "$BASE/api/auth/login"
            echo -n "GET /api/auth/me → "
            curl -s -o /dev/null -w '%{http_code}\n' -b "$c" "$BASE/api/auth/me"
          } | tee smoke_remote.txt

      - name: Upload smoke artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-remote
          path: smoke_remote.txt
          retention-days: 7

      - name: Kill tunnel
        if: always()
        run: |
          pids=$(lsof -tiTCP:18000 -sTCP:LISTEN || true)
          [[ -n "$pids" ]] && kill $pids || true
