name: Grant OS Login (wrapper)

on:
  workflow_dispatch:
    inputs:
      organization_id:
        description: YC organization id
        type: string
        required: true
      subject_type:
        description: "user | service_account"
        type: string
        required: true
      subject:
        description: "email (for user) or service-account id"
        type: string
        required: true

jobs:
  grant:
    uses: ./.github/workflows/yc-grant-oslogin.yml
    with:
      organization_id: ${{ inputs.organization_id }}
      subject_type:    ${{ inputs.subject_type }}
      subject:         ${{ inputs.subject }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit