name: yc-grant-oslogin-wrapper
on:
  workflow_dispatch:
    inputs:
      organization_id:
        description: YC organization id
        type: string
        required: true
      subject_type:
        description: "user | service_account"
        type: string
        required: true
      subject:
        description: "email (for user) or service-account id"
        type: string
        required: true
      os_login:
        description: "OS Login profile"
        type: string
        required: false
        default: yc-user
      uid:
        description: "Linux UID (string, will be fromJSON-ed)"
        type: string
        required: false
        default: "20000"
jobs:
  call:
    uses: ./.github/workflows/yc-grant-oslogin.yml
    with:
      organization_id: ${{ inputs.organization_id }}
      subject_type:    ${{ inputs.subject_type }}
      subject:         ${{ inputs.subject }}
      os_login:        ${{ inputs.os_login }}
      uid:             ${{ fromJSON(inputs.uid) }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
