name: Grant OS Login

on:
  workflow_call:
    inputs:
      organization_id: { type: string, required: true }
      subject_type:    { type: string, required: true }
      subject:         { type: string, required: true }

jobs:
  grant:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Show inputs (debug)
        run: |
          echo "ORG=${{ inputs.organization_id }}"
          echo "TYPE=${{ inputs.subject_type }}"
          echo "SUBJECT=${{ inputs.subject }}"
      # TODO: add real YC OS Login grant steps here
