name: Grant OS Login

on:
  workflow_call:
    inputs:
      organization_id: { type: string, required: true }
      subject_type:    { type: string, required: true }
      subject:         { type: string, required: true }
      os_login:        { type: string, required: false, default: yc-user }
      uid:             { type: number, required: false, default: 20000 }

jobs:
  grant:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Show inputs (debug)
        run: |
          echo "ORG=${{ inputs.organization_id }}"
          echo "TYPE=${{ inputs.subject_type }}"
          echo "SUBJECT=${{ inputs.subject }}"
          echo "OS_LOGIN=${{ inputs.os_login }}"
          echo "UID=${{ inputs.uid }}"
      # TODO: реальные шаги grant здесь
