name: yc-grant-oslogin
on:
  workflow_call:
    inputs:
      organization_id: { type: string, required: true }
      subject_type:    { type: string, required: true }
      subject:         { type: string, required: true }
      os_login:        { type: string, required: false, default: yc-user }
      uid:             { type: number, required: false, default: 20000 }
jobs:
  grant:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "ORG=${{ inputs.organization_id }}"
          echo "TYPE=${{ inputs.subject_type }}"
          echo "SUBJ=${{ inputs.subject }}"
          echo "OSL=${{ inputs.os_login }}"
          echo "UID=${{ inputs.uid }}"
      - name: Validate UID is number
        run: expr "${{ inputs.uid }}" + 0 >/dev/null 2>&1
      - name: Grant OS Login (stub)
        run: echo "Grant OS Login stub OK"
